services:
  postgres:
    image: postgres:17.9
    container_name: stock_market_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock_market

volumes:
  postgres_data: {}